apiVersion: v1
kind: Service
metadata:
  name: udacity-capstone-app-service
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  selector:
    app: udacity-capstone-app