version: 2.1
orbs:
  python: circleci/python@2.0.3
  heroku: circleci/heroku@1.2.6
commands:
  destroy-cluster:
    description: destroy cluster if needed
    parameters:
      workflowid:
        type: string
        default: ${CIRCLE_WORKFLOW_ID:0:7}
    steps:
      - run:
          name: install kubectl 
          when: on_fail
          command: |
            curl --silent --location "https://github.com/weaveworks/eksctl/releases/download/latest_release/eksctl_$(uname -s)_amd64.tar.gz" | tar xz -C /tmp
            sudo mv /tmp/eksctl /usr/local/bin
            echo "Destroying environment: <<parameters.workflowid>> "
      - run:
          name: destroy cluster
          when: on_fail
          command: |
            echo "Destroying environment: <<parameters.workflowid>> "
            eksctl delete -f cluster clusters/cluster.yml --region=us-east-1
  
  describe-cluster:
    description: describe cluster 
    parameters:
      workflowid:
        type: string
        default: ${CIRCLE_WORKFLOW_ID:0:7}
    steps:
      - run:
          name: describing the cluster
          command: |
            echo "getting cluster info"
            eksctl utils describe-stacks -f cluster clusters/cluster.yml --region=us-east-1

  cluster-status:
    description: get cluster status
    parameters:
      workflowid:
        type: string
        default: ${CIRCLE_WORKFLOW_ID:0:7}
    steps:
      - run:
          name: describing the cluster
          command: |
            echo "getting cluster info"
            eksctl get cluster -f cluster clusters/cluster.yml --region=us-east-1

jobs:
  build_and_test: # this can be any name you choose
    executor: python/default # use the default executor defined within the orb
    steps:
      - checkout # checkout source code
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Run tests
          command: python -m pytest
      - persist_to_workspace:
          root: ~/project
          paths:
            - .
  lint:
    docker:
    - image: docker:17.05.0-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - restore_cache:
          keys:
            - v1-{{ .Branch }}
      - run:
          name: Install dependencies
          command: |
            python3 -m venv .capstone
            . .capstone/bin/activate
            make install
      - save_cache:
          paths:
            - ./capstone  # TODO: Include in cache the "bin" directory
          key: v1-{{ .Branch }}-{{ epoch }}
      - run:
          name: Run lint
          command: |
            # Install hadolint
            . .capstone/bin/activate
            wget -O /bin/hadolint https://github.com/hadolint/hadolint/releases/download/v1.16.3/hadolint-Linux-x86_64 &&\
            chmod +x /bin/hadolint
            make lint

          
            
  build:
    docker:
    - image: python:3.7.3-stretch
      auth:
        username: marcolcal
        password: $DOCKER_PASSWORD
    steps:
      - checkout
      - restore_cache:
          keys: deployed-1
      - run: 
          name: "setting up env"
          command: |
            python3 -m venv venv
            . venv/bin/activate
            make install
      #- save_cache:
      #- paths:
          #- venv
  
          

#########LETS-
workflows: 
  default:
    jobs:
      - build_and_test
      - build
      - lint
      

 
      #- deploycluster:
      #    requires: [buildcontainer]
      #- pod-launcher:
      #    requires: [deploycluster]